name: NetGains Foundation
favicon: null
layout_spectrum: 0.20244700880721211
typography_spectrum: 0.3334521632641554
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1940997615456581
  lightness: 0.7323894556611776
  saturation: 0.7625687848776579
  rhythmicContrast: 0.4262286650482565
purpose: []
